version: '3.8'

services:
  app:
    build: .
    container_name: panagia_laravel_app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: panagia_laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PANAGIAsenha
      MYSQL_DATABASE: panagia_laravel
      MYSQL_USER: adminPanagia
      MYSQL_PASSWORD: EG13062009TY456
    ports:
      - "3307:3306"
    volumes:
      - db_laravel_data:/var/lib/mysql

volumes:
  db_laravel_data: